replicas: 2

rollingUpdate:
  maxSurge: 2
  maxUnavailable: 0

resources:
  memLimit: 12000Mi
  cpuRequest: 4
  memRequest: 8000Mi

image:
  identifier: <+artifacts.primary.image>
  imagePullPolicy: Always

service:
  http:
    internalPort: 5000
    externalPort: 80

secrets:
  slack:
    - SLACK_URL
