replicas: 2

rollingUpdate:
  maxSurge: 2
  maxUnavailable: 0

init:
  resources:
    memLimit: 6000Mi
    cpuRequest: 6
    memRequest: 4000Mi

resources:
  memLimit: 4000Mi
  cpuRequest: 200m
  memRequest: 2000Mi

image:
  identifier: <+artifacts.primary.image>
  imagePullPolicy: Always

service:
  http:
    internalPort: 5000
    externalPort: 80

secrets:
  slack:
    - SLACK_URL
